name: React Firebase CI/CD

on:
  push:
    branches:
      - master
jobs:
  build_test_deploy:
    runs-on: ubuntu-18.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.1
      - name: Install yarn Packages
        run: npm install
        working-directory: /home/firebase/test/
      - name: Build page
        run: npm run build
        working-directory: /home/firebase/test/
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
        working-directory: /home/firebase/test/
      - name: deploy to Firebase Hosting
        env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy  --only hosting --project prod --token $FIREBASE_TOKEN_PROD
        working-directory: app
