name: Deploy to firebase

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Setup the code
      run: npm install
      working-directory: test
    - name: Test the code
      run: npm test
      working-directory: test
    - name: Deploy to Firebase
      env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: firebase deploy  --only hosting --token $FIREBASE_TOKEN
      working-directory: app
      